### ISSUE TITLE
As a user, I want to filter offers by categories/tags/... [4h]

### ISSUE THREAD

**Issue by robinmamie** [SwengGolfTeam/Sweng_Golf#53]

**Comment by dingepfl** [comment]
We have a menu with the different Categories that can be opened from the `ListOfferActivity`, each one is checkable and on each change, the Offers are re-fetched from the Database in order to always have up-to-date info.
There is also a message if no Offers are matching the requested parameters and a progress bar is shown during the loading time from the Database.

![menucategories1](https://user-images.githubusercontent.com/36680622/47673200-3f749000-dbb4-11e8-8d4c-b1258f208916.png) ![menucategories2](https://user-images.githubusercontent.com/36680622/47673203-41d6ea00-dbb4-11e8-8bc0-ea7adc2bb013.png)

For more details see PR #88
